src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 */
class Article
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="text")
     */
    private $contenu;

    /**
     * @ORM\Column(type="datetime")
     */
    private $create_At;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    public function __construct()
    {
        $this->create_At=new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->create_At;
    }

    public function setCreateAt(\DateTimeInterface $create_At): self
    {
        $this->create_At = $create_At;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('titre')
            ->add('image', FileType::class,[
                'data_class'=>null
            ])
            ->add('contenu')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Form\ArticleType;
use App\Repository\ArticleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/article")
 */
class ArticleController extends AbstractController
{
    /**
     * @Route("/", name="article_index", methods={"GET"})
     */
    public function index(ArticleRepository $articleRepository): Response
    {
        return $this->render('article/index.html.twig', [
            'articles' => $articleRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="article_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $article = new Article();
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $picture = $form->get('image')->getData();
            $filenamepicture = 'image_' . md5(uniqid()) . '.' . $picture->guessExtension();
                try {
                    $picture->move($this->getParameter('images_directory'), $filenamepicture);
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }

            $article->setImage($filenamepicture);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($article);
            $entityManager->flush();

            return $this->redirectToRoute('article_index');
        }

        return $this->render('article/new.html.twig', [
            'article' => $article,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="article_show", methods={"GET"})
     */
    public function show(Article $article): Response
    {
        return $this->render('article/show.html.twig', [
            'article' => $article,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="article_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Article $article): Response
    {
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('article_index');
        }

        return $this->render('article/edit.html.twig', [
            'article' => $article,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="article_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Article $article): Response
    {
        if ($this->isCsrfTokenValid('delete'.$article->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($article);
            $entityManager->flush();
        }

        return $this->redirectToRoute('article_index');
    }
}

templates/article/_delete_form.html.twig
<form method="post" action="{{ path('article_delete', {'id': article.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.id) }}">
    <button class="btn">Delete</button>
</form>

templates/article/_form.html.twig
{{ form_start(form) }}
<div class="controls">
    <div class="row text-left">
        <div class="col-sm-12">
            <div class="form-group">
                <label for="prenom">Titre de l'article</label>
                {{ form_widget(form.titre, { 'attr': {'class': 'form-control'} } ) }}
            </div>
        </div>
        <div class="col-sm-12">
            <div class="form-group">
                <label for="prenom">Image</label>
                {{ form_widget(form.image) }}
            </div>
        </div>
        <div class="col-sm-12">
            <div class="form-group">
                <label for="prenom">Contenu</label>
                {{ form_widget(form.contenu, { 'attr': {'class': 'form-control'} } ) }}
            </div>
        </div>
    </div>
</div>
<div class="col-sm-12  text-center">
    <div id="success">
        <button id="submit" type="submit" name="submit" class="btn btn-medium-rsvp btn-block">Sauvegarder <i class="fa fa-long-arrow-right" aria-hidden="true"></i></button>
    </div>
</div>
{{ form_end(form) }}

templates/article/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Article{% endblock %}

{% block body %}
    <section id="reserve-image" class="v2 background-cover"  style="background-image: url('{{ asset('images/108.jpg')}}');" >
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <!-- MAIN TITLE WRAPPER -->
                    <div class="about-section-wraper text-center animated-element-1 delay1">
                        <h2>Modifier l'article</h2>

                    </div>
                    <!-- END MAIN TITLE WRAPPER -->
                </div>
            </div>
        </div>
    </section>
    <section id="reserve-form">
        <div class="container">
            <div class="row">
                <!-- SUSCRIBE FORM OUTER WRAPPER -->
                <div class="col-lg-10 col-lg-offset-1">
                    <!-- SUSCRIBE FORM INNER WRAPPER -->
                    <div class="block-box-rsrv">
                        <h1>Modifier l'article</h1>

                        {{ include('article/_form.html.twig', {'button_label': 'Update'}) }}
                        <a href="{{ path('article_index') }}">back to list</a>
                        {{ include('article/_delete_form.html.twig') }}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article index{% endblock %}

{% block body %}

    <!-- BLOG GALLERY CONTENT SECTION -->
    <section id="reserve-image" class="v2 background-cover"  style="background-image: url('{{ asset('images/108.jpg')}}');" >
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <!-- MAIN TITLE WRAPPER -->
                    <div class="about-section-wraper text-center animated-element-1 delay1">
                        <h2>Notre blog</h2>
                    </div>
                    <!-- END MAIN TITLE WRAPPER -->
                </div>
            </div>
        </div>
    </section>
    <section class="blog-content">
        <div class="container">
            <div class="row">
                <!--- BLOG HEADER WRAPPER -->
                {#<div class="row blgpadding">
                    <div class="col-md-6 col-xs-5">
                        <h2 class="blog-header-headline">Blog<span class="hidden-xs"> Standard</span></h2>
                    </div>
                    <div class="col-md-6 col-xs-7 text-right">
                        <h2 class="blog-header-headline">Le blog de notre évènnements,<span class="hidden-xs"> réagissez !</span></h2>
                    </div>
                </div>#}
                {% for article in articles %}

                <!-- BLOG-ITEM-4 -->
                    <div class="col-md-6 blog-image animated-element-1"  style="background-image:url({{ asset('images/'~article.image) }});">
                        <div class="blog-wraper text-left">
                            <!--LINK-->
                            <a href="{{path('article_show', {'id':article.id})}}">
                                <!-- TITLE & EXCERPT -->
                                <h3 class="">{{article.titre}}</h3>
                                <p>By Hanna & Chmouel on July 16, 2017 </p>
                                <p>Visionnez l'avancé des préparatifs  <br> et réagissez ! </p>
                                <div class="autors"> View Post <i class="fa fa-long-arrow-right" aria-hidden="true"></i> </div>
                                <!-- END TITLE & EXCERPT -->
                            </a>
                            <!-- END LINK-->
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>

    <a href="{{ path('article_new') }}">Create new</a>
{% endblock %}

templates/article/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Article{% endblock %}

{% block body %}
    <section id="reserve-image" class="v2 background-cover"  style="background-image: url('{{ asset('images/108.jpg')}}');" >
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <!-- MAIN TITLE WRAPPER -->
                    <div class="about-section-wraper text-center animated-element-1 delay1">
                        <h2>Nouvel article</h2>
                    </div>
                    <!-- END MAIN TITLE WRAPPER -->
                </div>
            </div>
        </div>
    </section>
<section id="reserve-form">
    <div class="container">
        <div class="row">
            <!-- SUSCRIBE FORM OUTER WRAPPER -->
            <div class="col-lg-10 col-lg-offset-1">
                <!-- SUSCRIBE FORM INNER WRAPPER -->
                <div class="block-box-rsrv">
                    <h1>Nouvel article</h1>

                    {{ include('article/_form.html.twig') }}

                    <a href="{{ path('article_index') }}">back to list</a>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/article/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article{% endblock %}

{% block body %}
    <section id="blog-header">
        <div class="container">
            <div class="row">
                <!--- BLOG TITLE WRAPPER -->
                <div class="col-md-12 text-center">
                    <!-- TITLE -->
                    <h1 class="headline">What's up</h1>
                    <!-- SPACER -->
                    <hr class="spacer">
                    <!-- TEXT INFO -->
                    <p class="subtitle">
                        30 juin 2020 by Hanna & Chmouel
                    </p>
                </div>
            </div>
        </div>
    </section>
<section id="about-content-single-post">
    <div class="container">
        <div class="row">
            <div class="col-md-12 blog-image img-responsive center-block animated-element-1 margin-single-post">
                <img class="img-responsive center-block" alt="500x500" src="{{ asset('images/1300x800.jpg') }}" data-holder-rendered="true">
            </div>
            <tbody>

                    {#<tr>
                        <th>Id</th>
                        <td>{{ article.id }}</td>
                    </tr>#}
                    {#<tr>
                        <th>Titre</th>
                        <td>{{ article.titre }}</td>
                    </tr>#}
                    <tr>
                        <table class="table">
                        {#<th>Contenu</th>#}
                            <td>{{ article.contenu }}</td>
                        </table>
                    </tr>
                    <tr>
                        <th>Create_At</th>
                        <td>{{ article.createAt ? article.createAt|date('Y-m-d H:i:s') : '' }}</td>
                    </tr>
                </tbody>
            </table>

    <a href="{{ path('article_index') }}">back to list</a>

    <a href="{{ path('article_edit', {'id': article.id}) }}">edit</a>

    {{ include('article/_delete_form.html.twig') }}
{% endblock %}